#!/bin/bash
#SBATCH --job-name=TestV100
#SBATCH --time=96:00:00
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:V100:2
#SBATCH --partition=m3g
source /home/cabe0006/mb20_scratch/chamath/detr/venv_detr/bin/activate
python -m torch.distributed.launch --nproc_per_node=2 --use_env main.py  --dataset_file ant --data_path /home/cabe0006/mb20_scratch/chamath/detr/dataset/ --output_dir /home/cabe0006/mb20_scratch/chamath/detr/output_batch
